### ISSUE TITLE
Position Social Buttons in <footer>

### ISSUE THREAD

**Issue by GionaFossati** [GionaFossati/GionaFossati.github.io#3]
Can't find the way to allign the buttons in the centre of the footer.
Any help?

**Comment by andrealeone** [comment]
Just created [branch #3](https://github.com/GionaFossati/GionaFossati.github.io/tree/%233) to solve the issue — I'm on it!

**Comment by GionaFossati** [comment]
Mee too! Just try to add `  left: 39%;
  margin-top: 30px;
  margin-left: 4px;`
To .social in main.css
It works but I don't like the solution, it's not flexible.
